export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEE';
export const FETCH_DEPARTMENT = 'FETCH_DEPARTMENT';